# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.8.5

pipelines:
  default:
    - parallel:
      - step:
          name: 'Python company api test'
          caches:
            - pip
          script:
            - pip install pipenv --upgrade
            - pipenv install --system
            - pytest api/learn_pytest -s -v --durations=0
      - step:
          name: 'Python fibonacci'
          caches:
            - pip
          script:
            - pip install pipenv --upgrade
            - pipenv install --system
            - pytest fibo -s -v --durations=0